-- MySQL Script generated by MySQL Workbench
-- sex 11 jul 2025 08:42:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `data_cadrasto` DATE NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filmes` (
  `idfilmes` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `duracao` INT NULL,
  `ano_lancamento` INT NULL,
  `classificacao` VARCHAR(45) NULL,
  `sinopse` VARCHAR(45) NULL,
  PRIMARY KEY (`idfilmes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assistido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`assistido` (
  `idassistido` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `filmes_idfilmes` INT NOT NULL,
  `data_assistido` DATE NOT NULL,
  PRIMARY KEY (`idassistido`),
  INDEX `fk_assistido_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_assistido_filmes1_idx` (`filmes_idfilmes` ASC) VISIBLE,
  CONSTRAINT `fk_assistido_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assistido_filmes1`
    FOREIGN KEY (`filmes_idfilmes`)
    REFERENCES `mydb`.`filmes` (`idfilmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LIstaDesejos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LIstaDesejos` (
  `idLIstaDesejos` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `filmes_idfilmes` INT NOT NULL,
  `data_adcionada` VARCHAR(45) NULL,
  PRIMARY KEY (`idLIstaDesejos`),
  INDEX `fk_LIstaDesejos_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_LIstaDesejos_filmes1_idx` (`filmes_idfilmes` ASC) VISIBLE,
  CONSTRAINT `fk_LIstaDesejos_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIstaDesejos_filmes1`
    FOREIGN KEY (`filmes_idfilmes`)
    REFERENCES `mydb`.`filmes` (`idfilmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assistindo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`assistindo` (
  `idassistindo` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `filmes_idfilmes` INT NOT NULL,
  `progresso` INT NULL,
  `data_inicio` VARCHAR(45) NULL,
  PRIMARY KEY (`idassistindo`),
  INDEX `fk_assistindo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_assistindo_filmes1_idx` (`filmes_idfilmes` ASC) VISIBLE,
  CONSTRAINT `fk_assistindo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assistindo_filmes1`
    FOREIGN KEY (`filmes_idfilmes`)
    REFERENCES `mydb`.`filmes` (`idfilmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;